export const errors = {
  UnkownError: -1,
  SettingsCouldNotLoad: 1,
  DesktopCouldNotLoad: 2,
  ParameterError: 3,
  NoResourceAccess: 4,
  ResourceDoesNotExist: 5,
  ProcessCrashed: 6,
  ProcessNotFound: 7,
  MessageBusNotFound: 8,
  MemoryAlreadyAllocated: 9,
  MemoryAllocationDoesNotExist: 10,
  NoWriteAccessToMemoryAddress: 11,
  NoReadAccessToMemoryAddress: 12,
  MessagebufferExceeded: 13,
  FiletypeNotExecutable: 14,
};

export enum Errors {
  NORESOURCEACCESS_OR_RESOURCENOTFOUND,
  RESOURCENOTFOUND,
  FILEHANDLENOTFOUND,
  FILELOCKED,
  FILEHANDLENOTINWRITEMODE,
  FILEWRITEERROR,
  INVALIDPARAMS,
  MEMORYALLOCATIONERROR,
  REMOVEFILEERROR,
  FREEMESSAGEBUSERROR,
  COULDNOTFINDPROCESS,
  PROCESSTERMINATED,
  COULDNOTOPENMESSAGEBUS,
  COULDNOTFINDMESSAGESESSION,
  RESOURCEREADONLY,
  RESOURCEWRITEONLY,
  MSGBUFFEREXCEEDED,
  COULDNOTSTARTPROCESS,
  FILETYPENOTEXECUTABLE,
  COULDNOTFINDUSER,
  CHANGEUSERNAMEERROR,
}

export const success = 0;
